[package]
name = "levers"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "^1.37", features = ["rt-multi-thread", "macros", "fs"] }
reqwest = { version = "^0.12", features = ["json"] }
graphql_client = { version = "^0.14" }
dotenvy = { version = "^0.15" }
serde = { version = "^1", features = ["derive"] }
serde_json = { version = "^1" }
clap = { version = "^4.5", features = ["derive"] }
